server:
  port: 8091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/furnace_db
    username: twin
    password: twin_secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092

websocket:
  topic:
    furnace: /topic/furnace
