server:
  port: 8085
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: furnace-service
          uri: lb://furnace-service
          predicates:
            - Path=/api/furnaces/**
          filters:
            - StripPrefix=1
        - id: alarm-service
          uri: lb://alarm-service
          predicates:
            - Path=/api/alarms/**
          filters:
            - StripPrefix=1
        - id: furnace-ws
          uri: lb:ws://furnace-service
          predicates:
            - Path=/ws/**
        - id: twin-state-service
          uri: lb://twin-state-service
          predicates:
            - Path=/api/twin/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:3001"
              - "http://localhost"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
        - name: CircuitBreaker
          args:
            name: defaultCB
            fallbackUri: forward:/fallback
resilience4j:
  timelimiter:
    instances:
      defaultCB:
        timeout-duration: 10s
  circuitbreaker:
    instances:
      defaultCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,gateway
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
