apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations: []

  - name: TimescaleDB
    type: postgres
    url: timescaledb:5432
    database: furnace_db
    user: twin
    secureJsonData:
      password: twin_secret
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: true
    editable: true

  - name: Elasticsearch
    type: elasticsearch
    url: http://elasticsearch:9200
    database: system_logs-*
    editable: true
    jsonData:
      esVersion: "8.0.0"
      timeField: "@timestamp"
      logMessageField: message
      logLevelField: level
