spring:
  data:
    redis:
      host: twin-redis
  datasource:
    url: jdbc:postgresql://twin-timescaledb:5432/furnace_db

eureka:
  client:
    service-url:
      defaultZone: http://twin-eureka:8761/eureka/
