server:
  port: 8091

spring:
  application:
    name: furnace-service
  config:
    import: "optional:configserver:http://localhost:8888"
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  datasource:
    url: jdbc:postgresql://localhost:5433/furnace_db
    username: twin
    password: twin_secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  health:
    db:
      enabled: false
    diskspace:
      enabled: false

logging:
  level:
    com.twin: DEBUG
